# Generated by Django 2.1.7 on 2019-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0007_auto_20190217_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
