# Generated by Django 2.1.7 on 2019-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0008_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='not provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='not provided', max_length=100),
            preserve_default=False,
        ),
    ]
